Models and validations for micro-Reddit
sjcco/micro-reddit pull request #1
Opened 2021-04-14 00:19 UTC by sjcco

- Create a model for user
- Create a model for post
- Create a model for comments
- Add validations for each model
- Add an association between models

2021-04-14 01:07 UTC, GzimAsani requested changes
STATUS: Changes Required :red_circle: 

### Hello @sjcco, great job with the project. Your project is working as expected and you have done good work in your model and with validations but you have to improve the following before moving on:
- [x] Add a descriptive readme ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

# HAPPY CODING :computer: :desktop_computer:

2021-04-15 17:30 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Carlos Campos Ojeda** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] I guess you were trying to make a list with dashes in the README file. Fix this so your README file looks ok. 

![](https://i.ibb.co/Yfjb9fg/review96.png)

- [ ] The how to set up the project is not complete. Make sure to provide all the necessary instructions.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-04-15 19:30 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Nice work making the requested changes. Let's make some changes to the readme.
I have left comments with suggestions.


### Martin Afani
#### Slack: whiz25

2021-04-15 19:30 UTC, whiz25 commented on README.md
> +-Clone the repo "https://github.com/sjcco/micro-reddit.git".
- Write the full command for cloning: `git clone ...`

2021-04-15 19:30 UTC, whiz25 commented on README.md
> +-Start adding users, posts and comments.
- How does one add a user. Add an example for adding users from the console. Always be explicit in your instructions.

2021-04-16 01:42 UTC, GzimAsani approved these changes
# STATUS: ACCEPTED :green_circle: :1st_place_medal: 

## Hello again @sjcco. Thank you for making all the required changes your project now looks complete and you readme looks professional. You may merge and good luck with the next projects :+1: 

_**Don't forget to submit the project completion form**_

# HAPPY CODING :computer: :desktop_computer:

2021-04-16 02:50 UTC, merged